name: Cleanup Staging

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  clean:
    runs-on: ubuntu-latest
    env:
      PULUMI_STACK_NAME: staging
    steps:
      - uses: actions/checkout@v2
      - uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: pulumi stack select $PULUMI_STACK_NAME
      - uses: pulumi/actions@v1
        with:
          command: destroy
