name: Deploy Staging

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  stage:
    runs-on: ubuntu-latest
    env:
      IS_PR_WORKFLOW: true
      COMMENT_ON_PR: 1
      PULUMI_STACK_NAME: staging
    steps:
      - uses: actions/checkout@v2
      - uses: pulumi/action-install-pulumi-cli@v1.0.1
      - run: pulumi stack select $PULUMI_STACK_NAME || pulumi stack init $PULUMI_STACK_NAME --copy-config-from dev
      - uses: pulumi/actions@v1
        with:
          command: preview
      - uses: pulumi/actions@v1
        with:
          command: up
